#include "nu32dip.h" // constants, functions for startup and UART
#include "stdio.h"
#include "i2c_master_noint.h"
#include "ssd1306.h"
#include "font.h"

#define FREQ_HZ_LED 1
#define DELAY_MS_LED ((float)(1000/FREQ_HZ_LED))
#define DELAY_CLOCK_LED (uint32_t)(24000 * DELAY_MS_LED)

void drawChar(char letter, char x, char y);
void drawString (char *m, char x, char y);

char pixel_val = 0;
char data_array[50];
char col;
char on_or_off;

int main(void) {
  NU32DIP_Startup(); // cache on, interrupts on, LED/button init, UART init
  i2c_master_setup();
  ssd1306_setup();
              
  while (1) {
      
      //blink LED and pixel of the OLED screen as a heartbeat signal
      //this takes a while so let it take the entire 
      _CP0_SET_COUNT(0);
      NU32DIP_GREEN = !NU32DIP_GREEN; 
      pixel_val = !pixel_val;
      ssd1306_drawPixel(127, 31, pixel_val);
      //ssd1306_update();
      
      if (pixel_val) {
          sprintf(data_array, "TESTING 1 2");
          drawString(data_array, 0, 0);
          ssd1306_update();
      } else {
          ssd1306_clear();
          ssd1306_update();
      }
      
      
      while (_CP0_GET_COUNT() < DELAY_CLOCK_LED) {/*nothing*/}
  }
}

void drawChar(char letter, char x, char y) {
	
	//loop through every ascii char in m
	for (int j = 0; j < 5; ++j) {
        char col = ASCII[letter - 0x20][j];
        for (int i = 0; i < 8; ++i) {
            //"and"ing it isolates our analysis to just showing 1 pixel at a time
            on_or_off = (col >> i) & 0b1; 
//            ssd1306_drawPixel(x + j, y + i, on_or_off); //draws a 1 if on or 0 if off
            if (on_or_off) {
                ssd1306_drawPixel(x + j, y + i, 1); //draws a 1 if on or 0 if off
            } else {
                ssd1306_drawPixel(x + j, y + i, 0); //draws a 1 if on or 0 if off

            }
        }
	}
}	

void drawString(char *m, char x, char y) {
	
	int k = 0;
	//iterate through the string until we get to the terminating
	//null character
	
	while (m[k] != 0) {
		drawChar(m[k], x + 5*k, y);
		++k;
	}
}


// blink both a LED and a pixel at 1Hz to 
//  verify that your system works. Keep the LED blink in your code, it 
//  is useful as a heartbeat 

  
//  Second, write a function that uses the font sample code to draw a 
//  letter at a position. The function should take in the position of 
//  the letter in x and y, and the character. font.h contains a bitmap 
//  of every drawable character in ASCII. Each letter is 8 pixels tall 
//  and 5 pixels wide. Loop through ASCII[the letter][column 1 to 5], 
//  turning pixels on when the bit is a 1 and off when the bit is a 0. 
//  Test it out.
  
  
//Third, write a function that prints a character array 
//generated by sprintf() at a position. The function should take in 
//the position of the first letter in x and y, and a pointer to the 
//character array. In the function, while the character is not the 
//null character ('\0' or the value 0) send the character to your 
//draw letter function with the right x and y position. Now you can 
//make a message and write to the screen:
//char message[50]; sprintf(message, "my var = %d", i); drawMessage(10,10,message); // draw starting at x=10,y=10

  
//Finally, write a program that prints the value of the z acceleration to 
//the screen. Set the core timer to 0 at the top of the loop, and read the
//value of the core timer after calling ssd1306_update(). Use the time 
//from the core timer to print to the bottom of the screen the frames per 
//second (fps) that the display can achieve.

